spring.application.name=contact-mgt


spring.datasource.url=jdbc:sqlserver://LAPTOP-04H2QBV7\SQLEXPRESS:1433;databaseName=ContactMgt;encrypt=true;trustServerCertificate=true
spring.datasource.username=LAPTOP-04H2QBV7\aniqa
spring.datasource.password=

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port=8080

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
#meaning if table is not there can create otherwise don't automatically
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Connection Pool (Hikari)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP

# generated password babea86c-14b1-471a-8857-d8a148702873

# JWT Config
jwt.secret=lwXrTUAQZ5wv1l2tHk2G6iribLXi09Wiek0nvmBk66/NBk2omNsOHYh4OuxTpwIY4Tlc8dWF56UWvppe3AW//Q==
jwt.expiration=3600000

# Logging
logging.level.root=WARN
logging.level.org.springframework.security=DEBUG
logging.level.com.aniqa.contact_mgt=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

cloudinary:
cloud-name: ${CLOUDINARY_CLOUD_NAME}
api-key: ${CLOUDINARY_API_KEY}
api-secret: ${CLOUDINARY_API_SECRET}

jwt:
secret: ${JWT_SECRET}
expiration: ${JWT_EXPIRATION}
